version: '3.2'

services:
  ad:
    build: .
    working_dir: /var/www/audiid_gl
    ports:
      - "9001:80"
    networks:
      - audeed.app
    depends_on:
      - db
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:c0XNCmy4scUAe9Jp90jpJCflN4ub0zff/JR0jQvzMDk=
      APP_DEBUG: 'true'
      APP_URL: https://gl.audeed.app
      LOG_CHANNEL: stack
      DB_CONNECTION: mysql
      DB_HOST: db  # Cambiado a 'db' para apuntar al servicio de base de datos en Docker
      DB_PORT: 3306
      DB_DATABASE: audiid_gl
      DB_USERNAME: ubuntu
      DB_PASSWORD: 4ud11dGl*
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      REDIS_HOST: redis  # Cambiado a 'redis' para apuntar al servicio Redis en Docker
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      MAIL_DRIVER: smtp
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: mailaudiit@gmail.com
      MAIL_PASSWORD: vsffvnooigbpziko
      MAIL_ENCRYPTION: tls
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET: ''
      PUSHER_APP_ID: ''
      PUSHER_APP_KEY: ''
      PUSHER_APP_SECRET: ''
      PUSHER_APP_CLUSTER: mt1
      MIX_PUSHER_APP_KEY: ${PUSHER_APP_KEY}
      MIX_PUSHER_APP_CLUSTER: ${PUSHER_APP_CLUSTER}
     
  db:
    image: mysql:latest
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: r0ot
      MYSQL_DATABASE: audiid_gl
      MYSQL_USER: ubuntu 
      MYSQL_PASSWORD: 4ud11dGl*
    ports:
      - "3366:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./respaldo.sql:/docker-entrypoint-initdb.d/respaldo.sql
    networks:
      - audeed.app

volumes:
  mysql_data: 

networks:
  audeed.app:
